name       : screen
version    : 4.8.0
release    : 16
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.8.0.tar.gz : 6e11b13d8489925fde25dfb0935bf6ed71f9eb47eff233a181e078fde5655aa1
license    : GPL-3.0-or-later
homepage   : https://www.gnu.org/software/screen/
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Screen is a full-screen window manager that multiplexes a physical terminal between several processes (typically inter‐active shells).
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2021-26937.patch
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
