name       : screen
version    : 4.9.0
release    : 18
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.9.0.tar.gz : f9335281bb4d1538ed078df78a20c2f39d3af9a4e91c57d084271e0289c730f4
license    : GPL-3.0-or-later
homepage   : https://www.gnu.org/software/screen/
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Screen is a full-screen window manager that multiplexes a physical terminal between several processes (typically inter‐active shells).
setup      : |
    %autogen --enable-colors256
build      : |
    %make
install    : |
    %make_install
