name       : screen
version    : 4.9.1
release    : 20
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.9.1.tar.gz : 26cef3e3c42571c0d484ad6faf110c5c15091fbf872b06fa7aa4766c7405ac69
license    : GPL-3.0-or-later
homepage   : https://www.gnu.org/software/screen/
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Screen is a full-screen window manager that multiplexes a physical terminal between several processes (typically inter‐active shells).
builddeps  :
    - pkgconfig(libxcrypt)
setup      : |
    %autogen --enable-colors256
build      : |
    %make
install    : |
    %make_install
