name        : screen
version     : 4.4.0
release     : 6
source     :
    - http://ftp.gnu.org/gnu/screen/screen-4.4.0.tar.gz : ef722a54759a3bf23aad272bbf33c414c1078cad6bcd982fada93c0d7917218b
license     :
    - GPLv2+
summary     : Full-screen window manager that multiplexes a physical terminal
description : |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
