name       : screen
version    : 4.7.0
release    : 13
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.7.0.tar.gz : da775328fa783bd2a787d722014dbd99c6093effc11f337827604c2efc5d20c1
license    : GPL-3.0-or-later
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Screen is a full-screen window manager that multiplexes a physical terminal between several processes (typically inter‐active shells).
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
