name        : screen
version     : 4.2.1
release     : 2
source      :
    - http://ftp.gnu.org/gnu/screen/screen-4.2.1.tar.gz : 5468545047e301d2b3579f9d9ce00466d14a7eec95ce806e3834a3d6b0b9b080
homepage    : http://www.gnu.org/software/screen/
license     :
    - GPLv2+
summary     : Full-screen window manager that multiplexes a physical terminal
description : |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
