name       : screen
version    : 4.5.0
release    : 8
source     :
    - http://ftp.gnu.org/gnu/screen/screen-4.5.0.tar.gz : 01c3a7c362185f35d6a95dff52d64337076496acd034d717de3c263500cfefb0
license    : GPL-2.0
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
