name        : screen
version     : 4.3.1
release     : 5
source     :
    - http://ftp.gnu.org/gnu/screen/screen-4.3.1.tar.gz : fa4049f8aee283de62e283d427f2cfd35d6c369b40f7f45f947dbfd915699d63
license     :
    - GPLv2+
summary     : Full-screen window manager that multiplexes a physical terminal
description : |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
