name       : screen
version    : 4.6.2
release    : 12
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.6.2.tar.gz : 1b6922520e6a0ce5e28768d620b0f640a6631397f95ccb043b70b91bb503fa3a
license    : GPL-2.0
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
