name       : screen
version    : 4.5.1
release    : 9
source     :
    - http://ftp.gnu.org/gnu/screen/screen-4.5.1.tar.gz : 97db2114dd963b016cd4ded34831955dcbe3251e5eee45ac2606e67e9f097b2d
license    : GPL-2.0
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
