name        : screen
version     : 4.3.0
release     : 3
source     :
    - http://ftp.gnu.org/gnu/screen/screen-4.3.0.tar.gz : 5164e89bcc60d7193177e6e02885cc42411d1d815c839e174fb9abafb9658c46
license     :
    - GPLv2+
summary     : Full-screen window manager that multiplexes a physical terminal
description : |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
