name       : screen
version    : 4.6.0
release    : 10
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.6.0.tar.gz : 9433706b653e941cc4c745f28e252e57be2a141eded923e61cc2c4a09768fed4
license    : GPL-2.0
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
