name       : screen
version    : 4.6.1
release    : 11
source     :
    - https://ftp.gnu.org/gnu/screen/screen-4.6.1.tar.gz : aba9af66cb626155d6abce4703f45cce0e30a5114a368bd6387c966cbbbb7c64
license    : GPL-2.0
component  : system.utils
summary    : Full-screen window manager that multiplexes a physical terminal
description: |
    Full-screen window manager that multiplexes a physical terminal
setup      : |
    %configure --enable-colors256
build      : |
    %make
install    : |
    %make_install
